### PR TITLE
GPL license

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by mortonjt** [comment]
@wasade mind if you could sanity check this once this passes?

**Comment by wasade** [comment]
Seems fine. Perhaps note in the changelog that it was realized ete was GPL, so adjusting as appropriate?

**Comment by mortonjt** [comment]
That's a good call.  Completely forgot about the CHANGELOG.  Added!

**Comment by mortonjt** [comment]
Want to merge?

**Comment by antgonza** [comment]
What about adding an issue to change to BSD once the ETE license changes?

**Comment by mortonjt** [comment]
Noted here #14

Is there anything else outstanding on this PR?

**Pull request merged**
