### PR TITLE
Update _formula.py

### PR DESCRIPTION
**Pull request by Josh-Lefler**
Added glm method and added exception for regression analysis in case of perfect separation.

The one time creation of a single exogenous (independent) variable table will reduce run-time significantly. It can be added to the other regression methods if needed.

### CODE REVIEW

**Comment by mortonjt** [comment]
Woooo.  Awesome!  Looks like there is some errors with travis.  I'll give detailed feedback tomorrow.

**Comment by mortonjt** [comment]
Hi @Josh-Lefler , is it possible to add a unittest to this?  A simple one to add is a comparison to OLS.  An example can be found [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/tests/test_glm.py#L210). 

I'd try to use the `ilr_inv` to back convert the real value numbers in the statsmodels tests into proportions.  I have a few examples this in the [mixedlm tests](https://github.com/biocore/gneiss/blob/master/gneiss/tests/test_formula.py#L252) as well as the [gee tests](https://github.com/mortonjt/gneiss/blob/7663336a86bddbfe409288a5490526e703ed1498/gneiss/tests/test_formula.py#L408).  

We don't need crazy tests, but we need a few tests to (1) sanity check the results and (2) make sure that no unexpected changes happen in the future.  

Also, looks like there are some pep8/flake8 errors.  I'd first install them as follows

```
pip install pep8 flake8
```
Then run them to catch these stylistic errors.

Let me know if there is any confusion.  Thanks!

**Comment by mortonjt** [comment]
Oh, before I forget, don't forget to update the `__init__.py`.  I'd look at this [PR](https://github.com/biocore/gneiss/pull/62/files) for more details on how to integrate additional functions into `_formala.py`

**Comment by mortonjt** [comment]
Hi @Josh-Lefler how's this PR going?

**Comment by mortonjt** [comment]
@Josh-Lefler I'm planning on finishing this PR this week and get merged.  All of your commits will be saved.  Are you ok with this?

**Comment by Josh-Lefler** [comment]
Hey Jamie!

That's totally fine. Sorry for the lack of communication, I thought my
major job was over once the app was complete but I'm now helping them
deploy it in Nigeria for a big project. We're almost done handing off the
reigns to all people in-country, so once this mess gets sorted out I am
down to help with any ideas you had in mind!

-Josh

**Pull request closed without merging**
