### PR TITLE
Addressing #77

### PR DESCRIPTION
**Pull request by mortonjt**
This is required for compatibility with qiime2

### CODE REVIEW

**Comment by mortonjt** [comment]
Ok, this is ready to merge!  @jkanbar want to do a review / merge this one?

**Comment by mortonjt** [comment]
@qiyunzhu would you also like to look at this?

**Comment by qiyunzhu** [comment]
I have discussed with @mortonjt . I think it is ready to merge.

**Comment by mortonjt** [comment]
Thanks!

**Pull request merged**
