### PR TITLE
Sphinx (#18)

### PR DESCRIPTION
**Pull request by mortonjt**
This addresses #18 and depends on #72 

Note that this is a pretty massive overhaul.  After we get this through and hosted on github pages, this will require a major release.

### CODE REVIEW

**Comment by mortonjt** [comment]
Not sure what is going on with coveralls here ...

**Comment by mortonjt** [comment]
The coveralls here is acting weird.  It actually looks like the coverage has increased rather than decreased :/

Regardless.  I don't think that this is a blocker.  Note that we do want to get this out fairly soon, since we want this out before the paper gets published.  Reviews would be greatly appreciated!

**Comment by mortonjt** [comment]
This is good to go.  @RNAer would you like to review/merge this?

**Comment by RNAer** [comment]
👍

**Pull request merged**
