### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mortonjt**
Addressing #65 and #68 

This is a pretty small PR that addresses the API change in scikit-bio with `ilr_inv`, in addition to the updating the existing documentation in the notebooks using the most up to date api.

### CODE REVIEW

**Comment by mortonjt** [comment]
@antgonza @wasade mind if you could do a pass over this and merge if ok?

**Comment by RNAer** [comment]
looks good to me

**Comment by mortonjt** [comment]
Thanks @RNAer !  Mind if you could merge?

**Comment by RNAer** [comment]
don't have permission

**Comment by mortonjt** [comment]
Thanks!

**Pull request merged**
