### PR TITLE
Correcting license headers

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by wasade** [comment]
At least [one](https://github.com/mortonjt/gneiss/blob/139e8fea8ad873b44b5fda568d973eaffc9678d7/setup.py#L67) more

**Comment by mortonjt** [comment]
gneiss catch!

**Comment by wasade** [comment]
:+1: once CI finishes

**Comment by mortonjt** [comment]
Awesome.  Want to merge?

**Pull request merged**
