### PR TITLE
BUG: Fixing Ilr fix

### PR DESCRIPTION
**Pull request by mortonjt**
There was an issue, where the tree wasn't properly aligned to the table when the ilr transform was applied (i.e. the tip names in the tree wasn't appropriately matched to the column names in the table).  So the ilr transform would be botched.

Note that this was only an issue for the new `ilr-transform` command in the CLI.

@antgonza do you mind if you could take a look at this PR?  The changes are very minimal

### CODE REVIEW

**Comment by antgonza** [comment]
looks good to me, 👍  when tests pass.

**Comment by mortonjt** [comment]
Looks like the errors are completely unrelated to this PR.

I'm currently cleaning up another PR in #174 to get rid of the q2 types that are throwing these errors.
So we'll probably want to merge that first.  Note that it has already been reviewed - so its just a matter of getting the tests to pass.

**Comment by antgonza** [comment]
note that this will break master, what about creating a new branch, where both prs are deployed?

**Comment by mortonjt** [comment]
I'm going to close this, since the fixes have been translated to #174

**Pull request closed without merging**
